import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className='antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900'>{children}</body>
    </html>
  )
}

export default RootLayout;
